---
abstract: 'Class for searching http://melcer.cz .'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Search-MelcerCZ
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Encode: 0
  LWP::UserAgent: 0
  Readonly: 0
  Text::Iconv: 0
  WWW::Search: 0
  Web::Scraper: 0
  perl: 5.6.2
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Search-MelcerCZ
  homepage: https://github.com/tupinek/WWW-Search-MelcerCZ
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/WWW-Search-MelcerCZ
version: '0.02'
